# M3U Editor with External M3U Proxy, Redis, and Gluetun VPN
# This setup routes the m3u-proxy through a VPN tunnel while keeping m3u-editor accessible
#
# Features:
# - PostgreSQL database for data persistence
# - External m3u-proxy container routed through Gluetun VPN
# - Redis for stream pooling and caching
# - Secure token-based authentication
# - VPN protection for streaming traffic
#
# Setup:
# 1. Copy this file to your project directory as docker-compose.yml
# 2. Create a .env file with the variables below
# 3. Configure your VPN provider settings (see Gluetun section below)
# 4. Run: docker-compose up -d
# 5. Access m3u-editor at http://localhost:36400
#
# Required Environment Variables (create .env file):
# M3U_PROXY_TOKEN=<generate with: openssl rand -hex 32>
# PG_PASSWORD=<generate with: openssl rand -base64 32>
# APP_URL=http://localhost  # or your domain
#
# VPN Configuration (choose one provider, see examples below):
# VPN_SERVICE_PROVIDER=nordvpn  # or mullvad, protonvpn, surfshark, etc.
# VPN_TYPE=openvpn  # or wireguard
# OPENVPN_USER=your_vpn_username
# OPENVPN_PASSWORD=your_vpn_password
# SERVER_COUNTRIES=United States  # Optional: specify country

services:
  m3u-editor:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args:
        GIT_BRANCH: ${GIT_BRANCH:-local}
        GIT_COMMIT: ${GIT_COMMIT:-local}
        GIT_TAG: ${GIT_TAG:-local}
    image: sparkison/m3u-editor:${IMAGE_TAG:-latest}
    container_name: m3u-editor
    # CRITICAL: Use Gluetun's network stack
    # This routes all m3u-editor traffic through the VPN
    network_mode: "service:gluetun"
    environment:
      # Timezone
      - TZ=Etc/UTC
      
      # Application URL (change to your domain or IP)
      - APP_URL=${APP_URL:-http://localhost}
      - APP_PORT=${APP_PORT:-36400}
      
      # Postgres Configuration
      - ENABLE_POSTGRES=true # Use embedded Postgres, disable to use your own Postgres service
      - PG_DATABASE=${PG_DATABASE:-m3ue}
      - PG_USER=${PG_USER:-m3ue}
      - PG_PASSWORD=${PG_PASSWORD:-changeme}
      - PG_PORT=${PG_PORT:-5432}
      
      # Database Connection (Laravel)
      - DB_CONNECTION=pgsql
      - DB_HOST=localhost
      - DB_PORT=${PG_PORT:-5432}
      - DB_DATABASE=${PG_DATABASE:-m3ue}
      - DB_USERNAME=${PG_USER:-m3ue}
      - DB_PASSWORD=${PG_PASSWORD:-changeme}

      # Redis configuration
      - REDIS_ENABLED=false # Disable embedded Redis instance
      - REDIS_SERVER_PORT=${REDIS_PORT:-6379}
      - REDIS_HOST=${REDIS_HOST:-127.0.0.1}
      
      # M3U Proxy Configuration (External)
      - M3U_PROXY_ENABLED=true # Enable external m3u-proxy
      - M3U_PROXY_PORT=${PROXY_PORT:-38085}
      - M3U_PROXY_HOST=${M3U_PROXY_HOST:-127.0.0.1} # Internal network hostname of m3u-proxy container
      # Public URL for m3u-proxy (used for rewriting stream URLs)
      - M3U_PROXY_PUBLIC_URL=${M3U_PROXY_PUBLIC_URL:-http://localhost:36400/m3u-proxy}
      - M3U_PROXY_TOKEN=${M3U_PROXY_TOKEN:-changeme}
    volumes:
      # Persistent configuration data
      - ./data:/var/www/config
      
      # PostgreSQL data persistence
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
      redis:
        condition: service_healthy
      m3u-proxy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${APP_PORT:-36400}/up"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # M3U Proxy - Runs inside Gluetun's network namespace
  # All traffic from this container goes through the VPN
  m3u-proxy:
    build:
      context: ../m3u-proxy
      dockerfile: Dockerfile
      target: runtime
      args:
        GIT_BRANCH: ${GIT_BRANCH:-local}
        GIT_COMMIT: ${GIT_COMMIT:-local}
        GIT_TAG: ${GIT_TAG:-local}
    image: sparkison/m3u-proxy:${IMAGE_TAG:-latest}
    container_name: m3u-proxy
    # CRITICAL: Use Gluetun's network stack
    # This routes all m3u-proxy traffic through the VPN
    network_mode: "service:gluetun"
    environment:
      # API Authentication Token (must match M3U_PROXY_TOKEN above)
      - API_TOKEN=${M3U_PROXY_TOKEN:-changeme}
      - PORT=${PROXY_PORT:-38085}

      # Redis Configuration (for stream pooling)
      - REDIS_ENABLED=true
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_HOST=${REDIS_HOST:-127.0.0.1}
      - REDIS_DB=6 # 1-5 used by m3u-editor, so use 6 for m3u-proxy
      - ENABLE_REDIS_POOLING=true
      
      # Logging
      - LOG_LEVEL=INFO

      # Public URL for re-writing HLS stream URLs
      # Set this to the public URL of your m3u-editor instance
      # Replace `m3u-editor` with your actual domain or LAN IP if needed so it is accessible to clients
      # NOTE: Make sure to add the `/m3u-proxy`
      - PUBLIC_URL=${M3U_PROXY_PUBLIC_URL:-http://localhost:36400/m3u-proxy}  # Change to your public URL if needed
      
      # Note: ROOT_PATH=/m3u-proxy is now the default, no need to set it explicitly
      # Only set ROOT_PATH= (empty) if you need to use the root path instead
      
      # Optional: Additional configuration
      # - REDIS_POOL_MAX_CONNECTIONS=50
      # - STREAM_TIMEOUT=300
      # - CLEANUP_INTERVAL=60
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${PROXY_PORT:-38085}/health?api_token=${M3U_PROXY_TOKEN:-changeme}"]
      interval: 30s
      timeout: 2s
      retries: 12
      start_period: 10s
    depends_on:
      gluetun:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Note: healthcheck removed because network_mode: service:gluetun 
    # means we can't directly healthcheck this container

  redis:
    image: redis:alpine3.22
    container_name: m3u-redis
    network_mode: "service:gluetun"
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 2s
      retries: 12

  # Gluetun VPN Container
  # All m3u-proxy traffic will be routed through this VPN tunnel
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/dri:/dev/dri  # Hardware acceleration for m3u-proxy
    ports:
      - ${APP_PORT:-36400}:${APP_PORT:-36400}  # M3U Editor port, change if needed

      # M3U Proxy port (exposed through Gluetun)
      # Uncomment if you need direct external access to m3u-proxy
      # - "${PROXY_PORT:-38085}:${PROXY_PORT:-38085}" # Change if needed
      
      # Gluetun control server (optional, for VPN management)
      # - "8000:8000/tcp"  # HTTP control server
    volumes:
      - gluetun-config:/gluetun
    environment:
      # VPN Configuration - CHOOSE YOUR PROVIDER
      # See https://github.com/qdm12/gluetun-wiki for all provider options
      # ...
    restart: unless-stopped

volumes:
  # PostgreSQL data volume
  pgdata:
    driver: local
    
  # Redis data volume
  redis-data:
    driver: local
    
  # Gluetun configuration volume
  gluetun-config:
    driver: local
